import Head from 'next/head'
import styled from 'styled-components'

export default function Home() {

  const Header = styled.header`
    position: fixed;
    top: 0;
    width: 100%;
    background-color: #fff;
    text-align: center;
    color: #1DADDC;
  `;

  const TopButton = styled.header`
    position: fixed;
    top: 0;
    width: 100%;
    background-color: #fff;
    text-align: center;
  `;

  const TopButtonDl = styled.a`
  `;

  const TopButtonDt = styled.header`
    display: inline-block;
    position: fixed;
    width: 100px;
    height: 100px;
    top: 0px;
    right: 0px;
    padding-left: 20px;
    padding: 40px 20px;
    margin-right: 10px;
    background-image: url(img/134058y.png);
    background-size: contain;
    background-repeat: no-repeat;
    font-size: 14px;
    cursor: pointer;
    color: #fff;
  `;

  const GlobalNav = styled.nav`
  `;
  const GlobalNavUl = styled.ul`
    position: fixed;
    top: 160px;
    right: 30px;
    padding-right: 18px;
    list-style: none;
  `;
  const GlobalNavLi = styled.li`
    font-size: 14px;
    font-weight: bold;
    text-transform: uppercase;
    letter-spacing: 2px;
    padding: 1.5em 0;
    writing-mode: vertical-lr;
    color: #ccc;
    text-decoration: none;
  `;
  const GlobalNavText = styled.a`
    color: #ccc;
    text-decoration: none;
  `;

  const Wrapper = styled.section`
    width: 900px;
    overflow: visible;
    margin: 0 auto;
    padding: 70px 0 0;
  `;
  const WorkSection = styled.section`
    padding: 80px 0px 80px;
    border-bottom: 1px solid #ccc;
    text-align: center;
  `;
  const WorkBox = styled.div`
    width: 750px;
    padding: 10px;
    margin: 0px auto;
    > img {
      display: inline-block;
    }
  `;
  const WorkBunner1 = styled.div`
    display: flex;
    justify-content: space-between;
  `;
  const WorkBunner2 = styled.div`
    margin-top: 20px;
    text-align: center;
    > img {
      margin-top: 20px;
    }
  `;
  const WorkTitle = styled.h2`
    color: #ccc;
  `;
  const WorkCategory = styled.h3`
    color: #ccc;
    margin-top: 20px;
    font-weight: bold;
    font-size: 16px;
  `;
  const WorkDetails = styled.h5`
    margin-top: 15px;
    color: #ccc;
    font-weight: normal;
  `;
  const WorkText = styled.p`
    margin: 30px auto 0px;
    padding: 0px 100px;
    text-align: center;
    color: #3E3A39;
  `;
  const WorkLink = styled.a`
    margin-top: 30px;
    display: block;
    text-align: center;
    color: #1DADDC;
    text-decoration: none;
  `;


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <Header>
          <h2>
            DOLPHIN DESIGNS
          </h2>
        </Header>

        <TopButton>
          <TopButtonDl id="accordion">
            <TopButtonDt>
              <p>top</p>
            </TopButtonDt>
          </TopButtonDl>
        </TopButton>

        <GlobalNav>
          <GlobalNavUl>
            <GlobalNavLi><GlobalNavText href="work.html">WORKS</GlobalNavText></GlobalNavLi>
            <GlobalNavLi><GlobalNavText href="https://recoben.wordpress.com" target="_blank">BLOG</GlobalNavText></GlobalNavLi>
            <GlobalNavLi><GlobalNavText href="https://docs.google.com/forms/d/e/1FAIpQLScWEUC0LHsy0vNGg_Nn2wfz05lRnRYkFFVAyRP4uTPbMABlfA/viewform?usp=sf_link" target="_blank">CONTACT</GlobalNavText></GlobalNavLi>
          </GlobalNavUl>
        </GlobalNav>

        <Wrapper>

          <WorkSection id="works_wolfpack">
            <WorkBox>
              <img src="img/azukaritai.png" alt="#" />
            </WorkBox>
            <WorkCategory>株式会社ユニバ</WorkCategory>
            <WorkTitle>azukaritai</WorkTitle>
            <WorkText>
              Vercelで展開するNext.jsでのコーディングの案件を頂きました。予算の都合でレスポンシブまでできないということでしたので、PCのみのコーディングにレスポンシブの動き方ができるように、ビューポートを活用したコーディング方法を取り入れました。モバイルでも崩れることなく希望通りの低予算で納品することができた案件でした。
            </WorkText>
            <WorkDetails>使用言語&amp;ツール: Next.js / Vercel / DartSass / Adobe Illustrator / Github /</WorkDetails>
            <WorkDetails>制作期間: 2021年12月</WorkDetails>
            <WorkLink href="https://www.azukaritai.com/" target="_blank">LINK</WorkLink>
          </WorkSection>

          <WorkSection id="works_wolfpack">
            <WorkBox>
              <img src="img/wolfpack.png" alt="#" />
            </WorkBox>
            <WorkCategory>Wolfpack Japan</WorkCategory>
            <WorkTitle>WOLFPACK</WorkTitle>
            <WorkText>
              レコードプレス会社の「かんたん見積り」画面、ナビ、ヘッダーなど、動的ページを主にReactとDartSassの組み込みとコーディングをしました。
            </WorkText>
            <WorkDetails>使用言語&amp;ツール: React / DartSass / Adobe Illustrator / Github /</WorkDetails>
            <WorkDetails>制作期間: 2021年6月~7月</WorkDetails>
            <WorkLink href="https://www.wolfpack-united.jp/" target="_blank">LINK</WorkLink>
          </WorkSection>

          <WorkSection id="works_QRATES2">
            <WorkBox>
              <img src="img/qrates2.png" alt="#" />
            </WorkBox>
            <WorkCategory>株式会社トウキョウ・デジタルミュージック・シンジケイツ</WorkCategory>
            <WorkTitle>QRATES</WorkTitle>
            <WorkText>QRATESの二度目の大幅リニューアルにフロントエンドエンジニアとして、参加させて頂きました。日本の開発チームに加え、ウクライナ、オーストラリア、フィリピンのデザイナーチーム＆エンジニアチームも加わりインターナショナルの環境の中での開発を経験しました。サイトの基礎となる主なコーディングやコンポーネントのルール作り、またコーディングスケジュールを作ってでの開発にも挑戦することができました。毎日、海外チームとオンラインでスプリントを回していく中で、自分が今まで気がつかなかったモダンな開発方法や、チームでの上流開発の楽しさを知りました。
            </WorkText>
            <WorkDetails>使用言語&amp;ツール: node-sass / slim / ruby on rails / React / bootstrap / sketch / realtimebord / Github / sourcetree</WorkDetails>
            <WorkDetails>制作期間: 2019年3月~2021年9月</WorkDetails>
            <WorkLink href="https://qrates.com/" target="_blank">LINK</WorkLink>
          </WorkSection>

          <WorkSection id="works_QRATES">
            <WorkBox>
              <img src="img/vej.png" alt="#" />
            </WorkBox>
            <WorkCategory>VISUAL AND ECHO JAPAN</WorkCategory>
            <WorkTitle>制作会社にて様々な案件に携わる</WorkTitle>
            <WorkText>コーダーとして、キャンペーンサイトやブランドのコーポレイトサイト、展示会のアプリや、顧客のECサイト制作、楽天市場での出店のサポートなど、様々な案件をコーディングをメインに携わらせた頂きました。
            </WorkText>
            <WorkDetails>使用言語&amp;ツール: node-sass / html / css / jquery / javascript / bootstrap / Photoshop / Illustrator / Github / sourcetree</WorkDetails>
            <WorkDetails>制作期間: 2018年4月~2018年10月</WorkDetails>
            <WorkLink href="https://v-e-j.com/" target="_blank">LINK</WorkLink>
          </WorkSection>

          <WorkSection id="works_QRATES">
            <WorkBox>
              <img src="img/qrates.jpg" alt="#" />
            </WorkBox>
            <WorkCategory>株式会社トウキョウ・デジタルミュージック・シンジケイツ</WorkCategory>
            <WorkTitle>QRATES</WorkTitle>
            <WorkText>フロントコーダーとして、アナログレコードを作りたい人のためのサイト「QRATES」のサイトリニューアルに関わらせて頂きまた。React, Ruby on railsの2つの構造の上、cssプリプロフェッサーはsass, bootstrapなどが混ざり合っていて分かりずらいのを解消すべく、bootstrapをはずしてflocssを基準にsassでコンポーネントを作り直しました。
            </WorkText>
            <WorkDetails>使用言語&amp;ツール: node-sass / slim / ruby on rails / React / bootstrap / sketch / realtimebord / Github / sourcetree</WorkDetails>
            <WorkDetails>制作期間: 2017年11月~2018年10月</WorkDetails>
            <WorkLink href="https://qrates.com/" target="_blank">LINK</WorkLink>
          </WorkSection>

          <WorkSection id="works_box">
            <WorkBox>
              <img src="img/ry_img.jpg " alt="#" />
            </WorkBox>
            <WorkCategory>卒業制作</WorkCategory>
            <WorkTitle>RHYTHM RECORDS</WorkTitle>
            <WorkText>訓練校の卒業制作にて、レコードレーベルのECサイトを作成しました。企画から、デザイン、ライティング、コーディング、jQueryの組み込みまで全て行い、モバイル対応も作成しました。</WorkText>
            <WorkDetails>使用ツール: Brackets / Adobe Illustrator CC 2015 / Photoshop CC 2015</WorkDetails>
            <WorkDetails>制作期間: 2017年11月~12月
              <br />
              企画 5 時間、デザイン 5 時間、コーディング 65 時間
            </WorkDetails>
            <WorkLink href="http://adjustacademy.com/d1707/d170707/rhythmrecords/index.html" target="_blank">LINK</WorkLink>
          </WorkSection>

          <WorkSection id="works_landing">
            <WorkBox>
              <img src="img/adjustin2.jpg " alt="# " />
            </WorkBox>
            <WorkCategory>訓練校課題</WorkCategory>
            <WorkTitle>ランディングページデザイン制作</WorkTitle>
            <WorkText>訓練校の課題制作で、カフェオーナー募集についてのランディングページのデザイン案を制作をしました。カフェの企画から、デザイン、制作、文章のライティングまで全て行いました。</WorkText>
            <WorkDetails>使用ツール:Adobe Illustrator CC 2015 / Photoshop CC 2015</WorkDetails>
            <WorkDetails>制作期間: 2017年9月
              <br />
              製作時間：企画 3 時間、デザイン 1 時間、制作 13 時間
            </WorkDetails>
            <WorkLink href="img/lp.jpg" target="_blank">LINK</WorkLink>
          </WorkSection>

          <WorkSection id="works_bunner">
            <WorkBox>
              <WorkBunner1>
                <img src="img/mr_1.jpg" alt="#" />
                <img src="img/mr_2.1.jpg" alt="#" />
                <img src="img/mr_3.jpg" alt="#" />  
              </WorkBunner1>
              <WorkBunner2>
                <img src="img/lb_1.gif" />
                <img src="img/lb_2.jpg" />
              </WorkBunner2>
            </WorkBox>
            <WorkCategory>訓練校課題</WorkCategory>
            <WorkTitle>バナー制作</WorkTitle>
            <WorkText>授業の課題にて、宅配野菜のキャンペーンのバナー作成をしました。食品サンプルの撮影から担当し、ターゲット設定をしたバナーを5つ制作しました。</WorkText>
            <WorkDetails>使用ツール:Photoshop CC 2015</WorkDetails>
            <WorkDetails>制作期間: 2017年8月
              <br />
              製作時間：撮影 2 時間、デザイン 1 時間、制作 14 時間
            </WorkDetails>
          </WorkSection>

          <WorkSection id="works_flier">
            <WorkBox>
              <WorkBunner1>
                <img src="img/flyer1.jpg" alt="# " />
                <img src="img/flyer2.jpg" alt="#" />
              </WorkBunner1>
            </WorkBox>
            <WorkCategory>訓練校課題</WorkCategory>
            <WorkTitle>フライヤー制作</WorkTitle>
            <WorkText>職業訓練校で主催している「子供プログラミング教室」のフライヤーを考え作成しました。Aiを使用してキャラクターを作り、見ていて楽しいフライヤーになるように心がけました。</WorkText>
            <WorkDetails>使用ツール:Adobe Illustrator CC 2015 / Photoshop CC 2015</WorkDetails>
            <WorkDetails>制作期間: 2017年10月
              <br />
              製作時間：キャラクター制作 3時間、他4時間
            </WorkDetails>
            <WorkLink href="flyer_01.pdf" target="_blank">PDFを見る</WorkLink>
          </WorkSection>

          <WorkSection>
            <WorkBox>
              <img src="img/satarege.jpg" alt="#" />
            </WorkBox>
            <WorkCategory>自主制作</WorkCategory>
            <WorkTitle>フライヤー制作</WorkTitle>
            <WorkText>友人が結成しているバンド”TUFF SESSION”のNew Albumのリリースパーティーのフライヤーを依頼され、担当しました。水彩色鉛筆と特殊なクレヨンを使った手書きのイラストを 背景に、Psを使用して地図や文字を配置しました。アルバムのメインの楽曲でもある「ツキノウタゲ」をモチーフにバンドの持つ、エキゾチックで不思議な可愛らさをイメージし表現しました。</WorkText>
            <WorkDetails>使用ツール:クレヨン / 水彩絵の具 / Adobe Photoshop CC 2015</WorkDetails>
            <WorkDetails>制作期間: 2016年8月
              <br />
              製作時間：イラスト作成 4 時間、文字入れ・編集 2 時間
            </WorkDetails>
          </WorkSection>

        </Wrapper>
      </main>
    </div>
  )
}
