name: Deploy to Amazon S3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install NPM dependencies
        run: npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: 'arn:aws:iam::583782972542:role/dolphindesigns-dev-EnterpriseLogAccessIamRole-KTQCBGB1DBWU'
          role-session-name: 'IRIE_IAMUSER'
      - name: Deploy Next.js app
        run: npx serverless
