name: Deploy to Amazon S3

on:
  push: # プルリクのマージもプッシュと同じ
    branches: [main] # ワークフロー起動対象のブランチ

jobs:
  build: # ジョブ名(名前は任意)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    timeout-minutes: 10 # デフォルトは360（6時間）のため短い時間で設定しておく
    
    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - run: npm test

      # - name: Checkout
      #   uses: actions/checkout@v2

      # - name: Setup Node
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 15.x
      #   run: npm ci
      #   run: npm run export

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-northeast-1
      #   run: aws s3 sync ./out s3://${{ secrets.AWS_BUCKET_NAME }}
