name: Deploy to Amazon S3

on:
  push: # プルリクのマージもプッシュと同じ
    branches: [main] # ワークフロー起動対象のブランチ

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [15.x]

#     timeout-minutes: 10
    
#     env:
#       NODE_ENV: production

#     steps:
#       - uses: actions/checkout@v1
#       - run: npm install
#       - run: npm run build
#       - run: npm test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        uses: actions/setup-node@v1
      - run: |
          npm install
          npm run generate
      # - uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      #     aws-region: ap-northeast-1
      # - name: Copy Files to s3
      #   run: |
      #     aws s3 sync ./dist s3://${{ secrets.S3_BUCKET }}
